#! /usr/bin/python3

from time import sleep
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import random

G2 = nx.read_pajek("Roget.net")
G3 = nx.Graph(G2)
G3.remove_edges_from(nx.selfloop_edges(G3))
G3.remove_nodes_from(list(nx.isolates(G3)))