#! /usr/bin/python3

from time import sleep
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import random

G2 = nx.read_pajek("Roget.net")
G3 = nx.Graph(G2)
G3.remove_edges_from(nx.selfloop_edges(G3))
G3.remove_nodes_from(list(nx.isolates(G3)))
G4 = nx.convert_node_labels_to_integers(G3)
num_neighbors = G3.number_of_nodes()

nr_nodes = 0
for i in G4.nodes:
    nr_nodes += len(list(G4.neighbors(i)))
print(nr_nodes/999)

#n_node = list(G4.neighbors(60))
#print(n_node)